<a href="https://colab.research.google.com/github/scott-huberty/LinAlgCourse/blob/remove_checkpoints/linalg_matrixMult.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#     COURSE: Linear algebra: theory and implementation
##    SECTION: Matrix multiplications

#### Instructor: sincxpress.com
##### Course url: https://www.udemy.com/course/linear-algebra-theory-and-implementation/?couponCode=202110

In [1]:
import numpy as np

In [21]:
m = 4
n = 6

A = np.random.rand(m, n)
B = np.random.rand(n, m)

# Build the product matrix layer-wise
C1 = np.zeros((m, m))
for i in range(n):
    C1 += np.outer(A[:, i], B[i, :])

# Implement matrix multiplication
C2 = A @ B

# Implement column perspective approach to matrix multiplication
C3 = np.zeros((m, m))
for i in range(m):
  for j in range(n):
    C3[:, i] += B[j, i] * A[:, j]


# Compare the results
print(np.allclose(C1, C2))

with np.printoptions(precision=3, suppress=True):  # supress scientific notation
  print(C3 - C2)

True
[[ 0.  0.  0.  0.]
 [ 0.  0.  0. -0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
