<a href="https://colab.research.google.com/github/scott-huberty/LinAlgCourse/blob/remove_checkpoints/matrixMults/linalg_matrixMult.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [6]:
m = 4
n = 6

A = np.random.rand(m, n)
B = np.random.rand(n, m)

# Build the product matrix layer-wise
C1 = np.zeros((m, m))
for i in range(n):
    C1 += np.outer(A[:, i], B[i, :])

# Implement matrix multiplication
C2 = A @ B

# Compare the results
print(np.allclose(C1, C2))

with np.printoptions(precision=3, suppress=True):
  print(C1 - C2)

True
[[ 0.  0. -0.  0.]
 [ 0. -0.  0.  0.]
 [-0.  0.  0.  0.]
 [ 0.  0.  0. -0.]]


In [7]:
np.get_printoptions()

{'edgeitems': 3,
 'threshold': 1000,
 'floatmode': 'maxprec',
 'precision': 8,
 'suppress': False,
 'linewidth': 75,
 'nanstr': 'nan',
 'infstr': 'inf',
 'sign': '-',
 'formatter': None,
 'legacy': False}