<a href="https://colab.research.google.com/github/scott-huberty/LinAlgCourse/blob/remove_checkpoints/matrixMults/lingalg_matrixRank_code_challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# challenge: Create 10x10 matrix with a rank of 4

# Key Ideas
#    - The maximum rank of a matrix is the minimum of the number of rows and columns.
#    - When Multiplying two matrices, the maximum rank of the resulting matrix is the minimum of the ranks of the two matrices.

A = np.random.randint(1, 3, size=(10, 4))
B = np.random.randint(1, 3, size=(4, 10))

C = A @ B

with np.printoptions(precision=3, suppress=True):
  print(C)

[[ 9  8  8  6  6  9  5  8  7  6]
 [12 10 11  9  9 12  7 11  9  8]
 [ 8  7  8  7  7  9  5  8  6  6]
 [ 9  8  8  6  6  9  5  8  7  6]
 [10  8  9  8  8 10  6  9  7  7]
 [12 10 11  9  9 12  7 11  9  8]
 [ 7  6  6  5  5  7  4  6  5  5]
 [12 10 11  9  9 12  7 11  9  8]
 [ 7  6  6  5  5  7  4  6  5  5]
 [10  9 10  8  8 11  6 10  8  7]]


In [3]:
C2 = np.zeros((10, 10), dtype=int)
for ri, row in enumerate(A):
  for ci, col in enumerate(B.T):
    this_elem = sum([Ai*Bi for Ai, Bi in zip(row, col)])
    C2[ri, ci] = this_elem

C2

array([[ 9,  8,  8,  6,  6,  9,  5,  8,  7,  6],
       [12, 10, 11,  9,  9, 12,  7, 11,  9,  8],
       [ 8,  7,  8,  7,  7,  9,  5,  8,  6,  6],
       [ 9,  8,  8,  6,  6,  9,  5,  8,  7,  6],
       [10,  8,  9,  8,  8, 10,  6,  9,  7,  7],
       [12, 10, 11,  9,  9, 12,  7, 11,  9,  8],
       [ 7,  6,  6,  5,  5,  7,  4,  6,  5,  5],
       [12, 10, 11,  9,  9, 12,  7, 11,  9,  8],
       [ 7,  6,  6,  5,  5,  7,  4,  6,  5,  5],
       [10,  9, 10,  8,  8, 11,  6, 10,  8,  7]])

In [4]:
np.linalg.matrix_rank(C2)

4